---

- name: install system updates for centos systems
  yum:
    name: {{ item }}
    state: latest
    update_cache: yes
  with_items:
    - git
    - php
  when: ansible_distribution == "CentOS"

- name: install system updates for ubuntu systems
  apt:
    name: {{ item }}
    state: latest
    update_cache: yes
  with_items:
    - git
    - php
  when: ansible_distribution == "Ubuntu"


- name: clone readis
  git:
    repo: 'https://github.com/hollodotme/readis.git'
    dest: /var
    version: v1.1.3

- name: get into right directory
  command: cat /var/readis
  register: readis

- name: run shell script
  shell: build/tools/update_tools.sh
  become: true

- name: run php file
  shell: 'php build/tools/composer.phar update -o -v'
  #args:
  #  chdir: 'build/tools'

- name: copy app file
  shell: 'cp config/app.sample.php config/app.php'
  become: true

- name:
  lineinfile:
    path: /var/readis/config/app.php
    regexp: '^'baseUrl' => '''
    line: ''baseUrl' => '192.168.1.1''
    backrefs: yes

- name: copy templete
  template:
    src: servers.j2
    dest: /var/readis/config/servers.php
  become: true

- name: copy templete
  template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf
  become: true
#- name: copy app file
#  shell: 'cp config/servers.sample.php config/servers.php'
#  become: true

- name: restart nginx
  service:
    name: nginx
    state: restarted
  tags:
    - always  
